<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="KF0224"><DocLocation><![CDATA[C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\02.公共脚本\信用速贷（build）]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[信用速贷（build）]]></DName>
<Res><![CDATA[Res36]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[5.3、风险参数]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[主窗口（浏览器）]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:01]]></Time>
<TimeTick>1551405721</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[一级窗口]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:01]]></Time>
<TimeTick>1551405721</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[一级窗口Page页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:01]]></Time>
<TimeTick>1551405721</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[DetailFrame_0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:01]]></Time>
<TimeTick>1551405721</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[DetailFrame_0.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:01]]></Time>
<TimeTick>1551405721</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" >
<Disp><![CDATA[DetailFrame_0.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ 风险参数 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:02]]></Time>
<TimeTick>1551405722</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ 风险参数 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" >
<Disp><![CDATA[DetailFrame_0]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" >
<Disp><![CDATA[一级窗口Page页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Internet Explorer ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:04]]></Time>
<TimeTick>1551405724</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" >
<Disp><![CDATA[[ Internet Explorer ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:15]]></Time>
<TimeTick>1551405735</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ WinButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2019/3/1 - 10:02:15]]></Time>
<TimeTick>1551405735</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="24" >
<Disp><![CDATA[[ WinButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ WinButton ].GetROProperty "disabled"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:17]]></Time>
<TimeTick>1551405797</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="38" status="Warning" >
<Disp><![CDATA[[ WinButton ].GetROProperty "disabled"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ WinButton ]]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 "[ WinButton ]" 对象的父对象 "[ Dialog ]" (类 Dialog)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:17]]></Time>
<TimeTick>1551405797</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>class name = Dialog<br>]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:17]]></Time>
<TimeTick>1551405797</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="40" status="Warning" nType="父对象的描述" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="39" status="Failed" nType="运行错误" >
<Disp><![CDATA[[ WinButton ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="23" status="Failed" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="12" status="Failed" >
<Disp><![CDATA[一级窗口]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="11" status="Failed" >
<Disp><![CDATA[主窗口（浏览器）]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 &quot;[ WinButton ]&quot; 对象的父对象 &quot;[ Dialog ]&quot; (类 Dialog)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。<BR>函数文件: C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl<BR>第 (31) 行: &quot;		If  ele.Exist(10) and ele.GetRoProperty(&quot;disabled&quot;)&lt;&gt;1 and ele.GetRoProperty(&quot;readonly&quot;)&lt;&gt;1 Then&quot;。]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:17]]></Time>
<TimeTick>1551405797</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="41" status="Failed" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl" SourceLine="-1" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[主窗口（浏览器）]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[一级窗口]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ WinButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl" SourceLine="-1" >
<Disp><![CDATA[[ WinButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ WinButton ].GetROProperty "disabled"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="67" status="Warning" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl" SourceLine="-1" >
<Disp><![CDATA[[ WinButton ].GetROProperty "disabled"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ WinButton ]]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 "[ WinButton ]" 对象的父对象 "[ Dialog ]" (类 Dialog)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>class name = Dialog<br>]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="69" status="Warning" nType="父对象的描述" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl" SourceLine="-1" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="68" status="Failed" nType="运行错误" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl" SourceLine="-1" >
<Disp><![CDATA[[ WinButton ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[停止运行]]></Obj>
<Details plainTxt="False" ><![CDATA[用户停止运行。]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<NodeArgs eType="General" icon="12" nRep="74" >
<Disp><![CDATA[停止运行]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="48" status="Failed" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl" SourceLine="-1" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="47" status="Failed" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl" SourceLine="-1" >
<Disp><![CDATA[一级窗口]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="46" status="Failed" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\04.函数库\Dialog.qfl" SourceLine="-1" >
<Disp><![CDATA[主窗口（浏览器）]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2019/3/1 - 10:01:55" eTime="2019/3/1 - 10:03:41" passed="0" failed="3" warnings="4" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[5.3、风险参数 摘要]]></Disp>
</NodeArgs>
</Action>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[停止运行]]></Obj>
<Details plainTxt="False" ><![CDATA[用户停止运行。]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:41]]></Time>
<TimeTick>1551405821</TimeTick>
<NodeArgs eType="General" icon="13" nRep="76" >
<Disp><![CDATA[停止运行]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2019/3/1 - 10:01:53" eTime="2019/3/1 - 10:03:41" passed="0" failed="3" warnings="4" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[测试 信用速贷（build） 摘要]]></Disp>
</NodeArgs>
</Doc>
</Report>