<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="KF0224"><DocLocation><![CDATA[C:\\Users\\922004\\Desktop\\孙洪斌\\学习文档集\\QTP脚本集\\基础脚本库\\南粤e贷1号（经营） - 副本]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[南粤e贷1号（经营） - 副本]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[0、参数]]></AName>
<Summary sTime="2018/5/8 - 11:03:49" eTime="2018/5/8 - 11:03:50" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[0、参数 摘要]]></Disp>
</NodeArgs>
</Action>
<Action rID="T5">
<AName><![CDATA[0、信用速贷]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ]]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 "[ WebEdit ]" 对象的父对象 "[ Browser ]" (类 Browser)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。]]></Details>
<Time><![CDATA[2018/5/8 - 11:04:12]]></Time>
<TimeTick>1525748652</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>Title = 信贷风险管理系统V7-登录窗口<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[2018/5/8 - 11:04:12]]></Time>
<TimeTick>1525748652</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" status="Warning" nType="父对象的描述" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="18" status="Failed" nType="运行错误" >
<Disp><![CDATA[[ WebEdit ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 &quot;[ WebEdit ]&quot; 对象的父对象 &quot;[ Browser ]&quot; (类 Browser)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。<BR>函数文件: C:\Users\922004\Desktop\孙洪斌\学习文档集\QTP脚本集\函数库\CreditLibrary.qfl<BR>第 (7) 行: &quot;	Browser(&quot;title:=信贷风险管理系统V7-登录窗口&quot;).Page(&quot;title:=信贷风险管理系统V7-登录窗口&quot;).WebEdit(&quot;name:=UserID&quot;).Set UserID&quot;。]]></Details>
<Time><![CDATA[2018/5/8 - 11:04:12]]></Time>
<TimeTick>1525748652</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" status="Failed" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\QTP脚本集\函数库\CreditLibrary.qfl" SourceLine="-1" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ WebButton ]]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 "[ WebButton ]" 对象的父对象 "[ Browser ]" (类 Browser)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。]]></Details>
<Time><![CDATA[2018/5/8 - 11:04:33]]></Time>
<TimeTick>1525748673</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>Title = 信贷风险管理系统V7-登录窗口<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[2018/5/8 - 11:04:33]]></Time>
<TimeTick>1525748673</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" status="Warning" nType="父对象的描述" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\QTP脚本集\函数库\CreditLibrary.qfl" SourceLine="-1" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="29" status="Failed" nType="运行错误" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\QTP脚本集\函数库\CreditLibrary.qfl" SourceLine="-1" >
<Disp><![CDATA[[ WebButton ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 &quot;[ WebButton ]&quot; 对象的父对象 &quot;[ Browser ]&quot; (类 Browser)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。<BR>函数文件: C:\Users\922004\Desktop\孙洪斌\学习文档集\QTP脚本集\函数库\CreditLibrary.qfl<BR>第 (8) 行: &quot;	Browser(&quot;title:=信贷风险管理系统V7-登录窗口&quot;).Page(&quot;title:=信贷风险管理系统V7-登录窗口&quot;).WebButton(&quot;type:=button&quot;,&quot;index:=0&quot;).Click&quot;。]]></Details>
<Time><![CDATA[2018/5/8 - 11:04:33]]></Time>
<TimeTick>1525748673</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" status="Failed" Source="C:\Users\922004\Desktop\孙洪斌\学习文档集\QTP脚本集\函数库\CreditLibrary.qfl" SourceLine="-1" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Action rID="T12">
<AName><![CDATA[1、面签流程]]></AName>
<Action rID="T13">
<AName><![CDATA[1.1、面签预约]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2018/5/8 - 11:04:36]]></Time>
<TimeTick>1525748676</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["信贷风险管理系统V7"  - 智能标识]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">已调用智能标识机制。</span></P><P><SPAN class=text>原因: 对象不唯一(已找到 2 个对象)</SPAN></P>           <SPAN class=text><b>原始描述:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>智能标识可选描述:</B></SPAN></FONT></P><FONT face=Verdana size=2><u>基本筛选属性(已找到 2 个对象) &nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>可选筛选属性</FONT></u><br>
name=信贷风险管理系统V7<SPAN class=Failed>(已跳过)</SPAN><br>title=信贷风险管理系统V7<SPAN class=Failed>(已跳过)</SPAN><br>openurl=http://11.8.121.150:7001/GDNY_CZ/logon.html<SPAN class=passed>(已使用</SPAN>，1 个匹配)</SPAN><br>opentitle=信贷风险管理系统V7-登录窗口<SPAN class=warning>(已忽略)<FONT color=#000000></FONT></SPAN><br>hasstatusbar=0<SPAN class=warning>(已忽略)<FONT color=#000000></FONT></SPAN><br>hasmenubar=-1<SPAN class=warning>(已忽略)<FONT color=#000000></FONT></SPAN><br>hastoolbar=-1<SPAN class=warning>(已忽略)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning>(已忽略)<FONT color=#000000></FONT></SPAN><br>number of tabs=2<SPAN class=warning>(已忽略)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2018/5/8 - 11:04:36]]></Time>
<TimeTick>1525748676</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" Source="1.1、面签预约" SourceLine="-1" >
<Disp><![CDATA["信贷风险管理系统V7"  - 智能标识]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:19]]></Time>
<TimeTick>1525748719</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[面签预约]]></Obj>
<Details plainTxt="False" ><![CDATA[无法标识对象 "面签预约" (属于类 WebElement)。验证此对象的属性与当前显示在应用程序中的对象是否匹配。]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:19]]></Time>
<TimeTick>1525748719</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[面签预约]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>Mercury Class = WebElement<br>Html Tag = SPAN<br>_xpath = //LI/UL/LI/UL/LI/A/SPAN[normalize-space()="面签预约"]<br>|Visible = 0<br>innertext = 面签预约<br>Html Id = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:19]]></Time>
<TimeTick>1525748719</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" status="Warning" nType="描述" Source="1.1、面签预约" SourceLine="-1" >
<Disp><![CDATA[面签预约]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="41" status="Failed" nType="运行错误" Source="1.1、面签预约" SourceLine="-1" >
<Disp><![CDATA[面签预约]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="40" status="Failed" Source="1.1、面签预约" SourceLine="-1" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="35" status="Failed" Source="1.1、面签预约" SourceLine="-1" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[无法标识对象 &quot;面签预约&quot; (属于类 WebElement)。验证此对象的属性与当前显示在应用程序中的对象是否匹配。<BR>第 (10) 行: &quot;Browser(&quot;信贷风险管理系统V7&quot;).Page(&quot;信贷风险管理系统V7&quot;).WebElement(&quot;面签预约&quot;).Click&quot;。 ]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:19]]></Time>
<TimeTick>1525748719</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" status="Failed" Source="1.1、面签预约" SourceLine="9" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:40]]></Time>
<TimeTick>1525748740</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[面签预约管理]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:40]]></Time>
<TimeTick>1525748740</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[right]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:40]]></Time>
<TimeTick>1525748740</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[新增预约]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 "新增预约" 对象的父对象 "right" (类 Frame)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:40]]></Time>
<TimeTick>1525748740</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[right]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>Mercury Class = Frame<br>|Url = http://11.8.121.150:7001/GDNY_CZ/ao?aoID=C2017110309120235502728114100024<br>Title = <br>Name = right<br>]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:40]]></Time>
<TimeTick>1525748740</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="92" status="Warning" nType="父对象的描述" Source="1.1、面签预约" SourceLine="9" >
<Disp><![CDATA[right]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="91" status="Failed" nType="运行错误" Source="1.1、面签预约" SourceLine="9" >
<Disp><![CDATA[新增预约]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="90" status="Failed" Source="1.1、面签预约" SourceLine="9" >
<Disp><![CDATA[right]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="89" status="Failed" Source="1.1、面签预约" SourceLine="9" >
<Disp><![CDATA[面签预约管理]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="88" status="Failed" Source="1.1、面签预约" SourceLine="9" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 &quot;新增预约&quot; 对象的父对象 &quot;right&quot; (类 Frame)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。<BR>第 (12) 行: &quot;.Frame(&quot;right&quot;).WebElement(&quot;新增预约&quot;).Click&quot;。 ]]></Details>
<Time><![CDATA[2018/5/8 - 11:05:40]]></Time>
<TimeTick>1525748740</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="93" status="Failed" Source="1.1、面签预约" SourceLine="11" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[客户姓名]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到 "客户姓名" 对象的父对象 "信贷风险管理系统V7" (类 Window)。验证父对象的属性与当前显示在应用程序中的对象是否匹配。]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>regexpwndtitle = 信贷风险管理系统V7 　　　　　　　　　　　　　　　　　 　　　　　　　　　　　　　　　　　 　　　　　　　　　　　　　　　　　 　　　　　　　　　　　　　　　　　 　　　　　　　　　　　　　　　　　 　　　　　　　　　　　　　　　　　 -- 网页对话框<br>regexpwndclass = Internet Explorer_TridentDlgFrame<br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="152" status="Warning" nType="父对象的描述" Source="1.1、面签预约" SourceLine="11" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="151" status="Failed" nType="运行错误" Source="1.1、面签预约" SourceLine="11" >
<Disp><![CDATA[客户姓名]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[停止运行]]></Obj>
<Details plainTxt="False" ><![CDATA[用户停止运行。]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<NodeArgs eType="General" icon="14" nRep="153" >
<Disp><![CDATA[停止运行]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="150" status="Failed" Source="1.1、面签预约" SourceLine="11" >
<Disp><![CDATA[myiframe0]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="149" status="Failed" Source="1.1、面签预约" SourceLine="11" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="148" status="Failed" Source="1.1、面签预约" SourceLine="11" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="147" status="Failed" Source="1.1、面签预约" SourceLine="11" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/5/8 - 11:04:35" eTime="2018/5/8 - 11:06:01" passed="0" failed="5" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="33" status="Failed" >
<Disp><![CDATA[1.1、面签预约 摘要]]></Disp>
</NodeArgs>
</Action>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[停止运行]]></Obj>
<Details plainTxt="False" ><![CDATA[用户停止运行。]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<NodeArgs eType="General" icon="14" nRep="155" >
<Disp><![CDATA[停止运行]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/5/8 - 11:04:35" eTime="2018/5/8 - 11:06:01" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="32" status="Failed" >
<Disp><![CDATA[1、面签流程 摘要]]></Disp>
</NodeArgs>
</Action>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[停止运行]]></Obj>
<Details plainTxt="False" ><![CDATA[用户停止运行。]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<NodeArgs eType="General" icon="14" nRep="157" >
<Disp><![CDATA[停止运行]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/5/8 - 11:03:51" eTime="2018/5/8 - 11:06:01" passed="0" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="9" status="Failed" >
<Disp><![CDATA[0、信用速贷 摘要]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[南粤e贷1号（经营） - 副本 迭代 1 (行 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[停止运行]]></Obj>
<Details plainTxt="False" ><![CDATA[用户停止运行。]]></Details>
<Time><![CDATA[2018/5/8 - 11:06:01]]></Time>
<TimeTick>1525748761</TimeTick>
<NodeArgs eType="General" icon="15" nRep="160" >
<Disp><![CDATA[停止运行]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/5/8 - 11:03:47" eTime="2018/5/8 - 11:06:01" passed="0" failed="9" warnings="5" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[测试 南粤e贷1号（经营） - 副本 摘要]]></Disp>
</NodeArgs>
</Doc>
</Report>