<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="KF0224"><DocLocation><![CDATA[C:\\Users\\922004\\Desktop\\孙洪斌\\学习文档集\\信贷脚本\\测试脚本\\信用速贷业务标准流程\\信用速贷标准流程驱动]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[信用速贷标准流程驱动]]></DName>
<Res><![CDATA[测试报告]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[信用速贷]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary 函数通过]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:47]]></Time>
<TimeTick>1525855127</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="7" status="Passed" Source="信用速贷" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary 函数通过]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:47]]></Time>
<TimeTick>1525855127</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="8" status="Passed" Source="信用速贷" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary 函数通过]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:47]]></Time>
<TimeTick>1525855127</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" Source="信用速贷" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[消费类标准工薪贷 [消费类标准工薪贷]]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ UserID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["008268"]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:50]]></Time>
<TimeTick>1525855130</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[[ UserID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:50]]></Time>
<TimeTick>1525855130</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" >
<Disp><![CDATA[[ WebButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Action rID="T10">
<AName><![CDATA[1、面签流程 [信用速贷]]]></AName>
<Action rID="T11">
<AName><![CDATA[1.1、面签预约 [信用速贷]]]></AName>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:55]]></Time>
<TimeTick>1525855135</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:55]]></Time>
<TimeTick>1525855135</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[面签预约.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:55]]></Time>
<TimeTick>1525855135</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="23" >
<Disp><![CDATA[面签预约.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="22" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[面签预约管理]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:56]]></Time>
<TimeTick>1525855136</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[right]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:56]]></Time>
<TimeTick>1525855136</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[新增预约.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:38:56]]></Time>
<TimeTick>1525855136</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="28" >
<Disp><![CDATA[新增预约.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="27" >
<Disp><![CDATA[right]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="26" >
<Disp><![CDATA[面签预约管理]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[客户姓名.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" >
<Disp><![CDATA[客户姓名.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[客户姓名.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["张八"]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" >
<Disp><![CDATA[客户姓名.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[身份证号码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" >
<Disp><![CDATA[身份证号码.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[身份证号码.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["350202199001011153"]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" >
<Disp><![CDATA[身份证号码.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[雇佣类型.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="43" >
<Disp><![CDATA[雇佣类型.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[雇佣类型.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["标准受薪客户"]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="45" >
<Disp><![CDATA[雇佣类型.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[贷款品种.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:00]]></Time>
<TimeTick>1525855140</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="47" >
<Disp><![CDATA[贷款品种.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="34" >
<Disp><![CDATA[myiframe0]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="33" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[请选择所需信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[请选择所需信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[left]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ 消费类标准工薪贷 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" >
<Disp><![CDATA[[ 消费类标准工薪贷 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="53" >
<Disp><![CDATA[left]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[确认.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="56" >
<Disp><![CDATA[确认.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="52" >
<Disp><![CDATA[请选择所需信息]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="51" >
<Disp><![CDATA[请选择所需信息]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[申请金额.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="60" >
<Disp><![CDATA[申请金额.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[申请金额.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["200000"]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" >
<Disp><![CDATA[申请金额.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[贷款申请期限.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:04]]></Time>
<TimeTick>1525855144</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="64" >
<Disp><![CDATA[贷款申请期限.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[贷款申请期限.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["24"]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:05]]></Time>
<TimeTick>1525855145</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="66" >
<Disp><![CDATA[贷款申请期限.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[客户经理.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:05]]></Time>
<TimeTick>1525855145</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="68" >
<Disp><![CDATA[客户经理.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="59" >
<Disp><![CDATA[myiframe0]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="58" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[请选择所需信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:08]]></Time>
<TimeTick>1525855148</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[请选择所需信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:08]]></Time>
<TimeTick>1525855148</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:08]]></Time>
<TimeTick>1525855148</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[R0F0.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:08]]></Time>
<TimeTick>1525855148</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" >
<Disp><![CDATA[R0F0.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="74" >
<Disp><![CDATA[myiframe0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[确认.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:08]]></Time>
<TimeTick>1525855148</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="77" >
<Disp><![CDATA[确认.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="73" >
<Disp><![CDATA[请选择所需信息]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="72" >
<Disp><![CDATA[请选择所需信息]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:10]]></Time>
<TimeTick>1525855150</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:10]]></Time>
<TimeTick>1525855150</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[城市.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:10]]></Time>
<TimeTick>1525855150</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="81" >
<Disp><![CDATA[城市.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[城市.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["广州"]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:10]]></Time>
<TimeTick>1525855150</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="83" >
<Disp><![CDATA[城市.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[初始预约时间.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:10]]></Time>
<TimeTick>1525855150</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" >
<Disp><![CDATA[初始预约时间.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="80" >
<Disp><![CDATA[myiframe0]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="79" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[-- 网页对话框]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[时间.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="92" >
<Disp><![CDATA[时间.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[时间.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["16:00"]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="94" >
<Disp><![CDATA[时间.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="91" >
<Disp><![CDATA[myiframe0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[确认.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="96" >
<Disp><![CDATA[确认.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="90" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="89" >
<Disp><![CDATA[-- 网页对话框]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[ObjectList]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[保存.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:14]]></Time>
<TimeTick>1525855154</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="101" >
<Disp><![CDATA[保存.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="100" >
<Disp><![CDATA[ObjectList]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="99" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="32" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:17]]></Time>
<TimeTick>1525855157</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="103" >
<Disp><![CDATA[信贷风险管理系统V7.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[面签预约管理]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:18]]></Time>
<TimeTick>1525855158</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:18]]></Time>
<TimeTick>1525855158</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ R0F1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:18]]></Time>
<TimeTick>1525855158</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="108" >
<Disp><![CDATA[[ R0F1 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="107" >
<Disp><![CDATA[myiframe0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[right]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:18]]></Time>
<TimeTick>1525855158</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[提交.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:18]]></Time>
<TimeTick>1525855158</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="111" >
<Disp><![CDATA[提交.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="110" >
<Disp><![CDATA[right]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="106" >
<Disp><![CDATA[面签预约管理]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[提交动作选择列表 -- 网页对话框]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:21]]></Time>
<TimeTick>1525855161</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[提交动作选择列表]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:21]]></Time>
<TimeTick>1525855161</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[提交.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:21]]></Time>
<TimeTick>1525855161</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="117" >
<Disp><![CDATA[提交.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="116" >
<Disp><![CDATA[提交动作选择列表]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[来自网页的消息]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:24]]></Time>
<TimeTick>1525855164</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[确定.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:24]]></Time>
<TimeTick>1525855164</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="121" >
<Disp><![CDATA[确定.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[确定.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:25]]></Time>
<TimeTick>1525855165</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="123" >
<Disp><![CDATA[确定.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="120" >
<Disp><![CDATA[来自网页的消息]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="115" >
<Disp><![CDATA[提交动作选择列表 -- 网页对话框]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="21" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/5/9 - 16:38:55" eTime="2018/5/9 - 16:39:25" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="8" nRep="18" >
<Disp><![CDATA[1.1、面签预约 [信用速贷] 摘要]]></Disp>
</NodeArgs>
</Action>
<Action rID="T71">
<AName><![CDATA[1.2、面签排班 [信用速贷]]]></AName>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[面签排班管理]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:26]]></Time>
<TimeTick>1525855166</TimeTick>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[面签排班管理]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:26]]></Time>
<TimeTick>1525855166</TimeTick>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[面签排班.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:26]]></Time>
<TimeTick>1525855166</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="130" >
<Disp><![CDATA[面签排班.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:35]]></Time>
<TimeTick>1525855175</TimeTick>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[[ R0F1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:35]]></Time>
<TimeTick>1525855175</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="134" >
<Disp><![CDATA[[ R0F1 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="133" >
<Disp><![CDATA[myiframe0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[right]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:35]]></Time>
<TimeTick>1525855175</TimeTick>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[任务详情.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:35]]></Time>
<TimeTick>1525855175</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="137" >
<Disp><![CDATA[任务详情.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="136" >
<Disp><![CDATA[right]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="129" >
<Disp><![CDATA[面签排班管理]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:38]]></Time>
<TimeTick>1525855178</TimeTick>
<Step rID="T80">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:38]]></Time>
<TimeTick>1525855178</TimeTick>
<Step rID="T81">
<Obj plainTxt="False" ><![CDATA[ObjectList]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:38]]></Time>
<TimeTick>1525855178</TimeTick>
<Step rID="T82">
<Obj plainTxt="False" ><![CDATA[保存.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:38]]></Time>
<TimeTick>1525855178</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="144" >
<Disp><![CDATA[保存.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="143" >
<Disp><![CDATA[ObjectList]]></Disp>
</NodeArgs>
</Step>
<Step rID="T83">
<Obj plainTxt="False" ><![CDATA[Close 关闭.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:39]]></Time>
<TimeTick>1525855179</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="147" >
<Disp><![CDATA[Close 关闭.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="142" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="141" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T84">
<Obj plainTxt="False" ><![CDATA[面签排班管理.刷新所有选项卡]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:46]]></Time>
<TimeTick>1525855186</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="149" >
<Disp><![CDATA[面签排班管理.刷新所有选项卡]]></Disp>
</NodeArgs>
</Step>
<Step rID="T85">
<Obj plainTxt="False" ><![CDATA[面签排班管理]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:53]]></Time>
<TimeTick>1525855193</TimeTick>
<Step rID="T86">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:53]]></Time>
<TimeTick>1525855193</TimeTick>
<Step rID="T87">
<Obj plainTxt="False" ><![CDATA[[ R0F1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018/5/9 - 16:39:53]]></Time>
<TimeTick>1525855193</TimeTick>