<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="PACTERA-PC"><DocLocation><![CDATA[E:\DataOfSoftWare\Unified Functional Testing\信用速贷]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[信用速贷]]></DName>
<Res><![CDATA[Res58]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[1、登录]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7-登录窗口]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:07]]></Time>
<TimeTick>1507627147</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7-登录窗口]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:07]]></Time>
<TimeTick>1507627147</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[用户名ID.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["008036"]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:07]]></Time>
<TimeTick>1507627147</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="1、登录" SourceLine="0" >
<Disp><![CDATA[用户名ID.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1439.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7-登录窗口").Page("信贷风险管理系统V7-登录窗口").WebEdit("用户名ID")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:07]]></Time>
<TimeTick>1507627147</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" Source="1、登录" SourceLine="1" >
<Disp><![CDATA[登录.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1440.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7-登录窗口").Page("信贷风险管理系统V7-登录窗口").WebButton("登录")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="1、登录" SourceLine="0" >
<Disp><![CDATA[信贷风险管理系统V7-登录窗口]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1438.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7-登录窗口").Page("信贷风险管理系统V7-登录窗口")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="1、登录" SourceLine="0" >
<Disp><![CDATA[信贷风险管理系统V7-登录窗口]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/10/10 - 17:19:07" eTime="2017/10/10 - 17:19:07" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[1、登录 摘要]]></Disp>
</NodeArgs>
</Action>
<Action rID="T9">
<AName><![CDATA[2、面签预约]]></AName>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:09]]></Time>
<TimeTick>1507627149</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:09]]></Time>
<TimeTick>1507627149</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[面签预约.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:09]]></Time>
<TimeTick>1507627149</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="2、面签预约" SourceLine="1" >
<Disp><![CDATA[面签预约.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1442.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Page("信贷风险管理系统V7").Link("面签预约")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="21" Source="2、面签预约" SourceLine="1" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1441.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Page("信贷风险管理系统V7")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[面签预约管理]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:10]]></Time>
<TimeTick>1507627150</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[新增预约]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:10]]></Time>
<TimeTick>1507627150</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[新增预约.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:10]]></Time>
<TimeTick>1507627150</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="27" Source="2、面签预约" SourceLine="2" >
<Disp><![CDATA[新增预约.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1445.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Page("面签预约管理").Frame("新增预约").WebElement("新增预约")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="26" Source="2、面签预约" SourceLine="2" >
<Disp><![CDATA[新增预约]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1444.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Page("面签预约管理").Frame("新增预约")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="2、面签预约" SourceLine="2" >
<Disp><![CDATA[面签预约管理]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1443.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Page("面签预约管理")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:13]]></Time>
<TimeTick>1507627153</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:14]]></Time>
<TimeTick>1507627154</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:14]]></Time>
<TimeTick>1507627154</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[客户姓名.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:14]]></Time>
<TimeTick>1507627154</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="2、面签预约" SourceLine="4" >
<Disp><![CDATA[客户姓名.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1449.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebEdit("客户姓名")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[客户姓名.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ceshi"]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:14]]></Time>
<TimeTick>1507627154</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="2、面签预约" SourceLine="5" >
<Disp><![CDATA[客户姓名.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1450.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebEdit("客户姓名")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[身份证号码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:14]]></Time>
<TimeTick>1507627154</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="2、面签预约" SourceLine="6" >
<Disp><![CDATA[身份证号码.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1451.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebEdit("身份证号码")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[身份证号码.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["511423198710100019"]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:14]]></Time>
<TimeTick>1507627154</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="2、面签预约" SourceLine="7" >
<Disp><![CDATA[身份证号码.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1452.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebEdit("身份证号码")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[雇佣类型选择框.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["标准受薪客户"]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:14]]></Time>
<TimeTick>1507627154</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="46" Source="2、面签预约" SourceLine="8" >
<Disp><![CDATA[雇佣类型选择框.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1453.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebList("雇佣类型选择框")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[贷款品种选择按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:14]]></Time>
<TimeTick>1507627154</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="49" Source="2、面签预约" SourceLine="9" >
<Disp><![CDATA[贷款品种选择按钮.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1454.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebButton("贷款品种选择按钮")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="33" Source="2、面签预约" SourceLine="4" >
<Disp><![CDATA[myiframe0]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1448.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" Source="2、面签预约" SourceLine="4" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1447.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[请选择所需信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:17]]></Time>
<TimeTick>1507627157</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[请选择所需信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:17]]></Time>
<TimeTick>1507627157</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[left]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[消费类标准信用速贷.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="56" Source="2、面签预约" SourceLine="10" >
<Disp><![CDATA[消费类标准信用速贷.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1458.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("请选择所需信息").Page("请选择所需信息").Frame("left").WebElement("消费类标准信用速贷")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="55" Source="2、面签预约" SourceLine="10" >
<Disp><![CDATA[left]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1457.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("请选择所需信息").Page("请选择所需信息").Frame("left")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[确认.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="59" Source="2、面签预约" SourceLine="11" >
<Disp><![CDATA[确认.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1459.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("请选择所需信息").Page("请选择所需信息").WebButton("确认")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="54" Source="2、面签预约" SourceLine="10" >
<Disp><![CDATA[请选择所需信息]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1456.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("请选择所需信息").Page("请选择所需信息")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="53" Source="2、面签预约" SourceLine="10" >
<Disp><![CDATA[请选择所需信息]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1455.xml]]></Path>
<ASHilite><![CDATA[203136]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[贷款期限输入框.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="65" Source="2、面签预约" SourceLine="12" >
<Disp><![CDATA[贷款期限输入框.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1462.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebEdit("贷款期限输入框")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[贷款期限输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["12"]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="69" Source="2、面签预约" SourceLine="13" >
<Disp><![CDATA[贷款期限输入框.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1463.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebEdit("贷款期限输入框")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[贷款金额.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="72" Source="2、面签预约" SourceLine="14" >
<Disp><![CDATA[贷款金额.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1464.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebEdit("贷款金额")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[贷款金额.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["40000"]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:18]]></Time>
<TimeTick>1507627158</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="75" Source="2、面签预约" SourceLine="15" >
<Disp><![CDATA[贷款金额.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1465.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebEdit("贷款金额")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[客户经理选择按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:19]]></Time>
<TimeTick>1507627159</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="78" Source="2、面签预约" SourceLine="16" >
<Disp><![CDATA[客户经理选择按钮.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1466.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebButton("客户经理选择按钮")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="64" Source="2、面签预约" SourceLine="12" >
<Disp><![CDATA[myiframe0]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1461.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="63" Source="2、面签预约" SourceLine="12" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1460.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[请选择所需信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:22]]></Time>
<TimeTick>1507627162</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[请选择所需信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:22]]></Time>
<TimeTick>1507627162</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:22]]></Time>
<TimeTick>1507627162</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[选择的客户经理.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:22]]></Time>
<TimeTick>1507627162</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" Source="2、面签预约" SourceLine="17" >
<Disp><![CDATA[选择的客户经理.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1470.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("请选择所需信息").Page("请选择所需信息").Frame("myiframe0").WebEdit("选择的客户经理")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="84" Source="2、面签预约" SourceLine="17" >
<Disp><![CDATA[myiframe0]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1469.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("请选择所需信息").Page("请选择所需信息").Frame("myiframe0")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[确认.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:22]]></Time>
<TimeTick>1507627162</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="88" Source="2、面签预约" SourceLine="18" >
<Disp><![CDATA[确认.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1471.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("请选择所需信息").Page("请选择所需信息").WebButton("确认")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="83" Source="2、面签预约" SourceLine="17" >
<Disp><![CDATA[请选择所需信息]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1468.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("请选择所需信息").Page("请选择所需信息")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="82" Source="2、面签预约" SourceLine="17" >
<Disp><![CDATA[请选择所需信息]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1467.xml]]></Path>
<ASHilite><![CDATA[334038]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:22]]></Time>
<TimeTick>1507627162</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:22]]></Time>
<TimeTick>1507627162</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[最终预约时间选择按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:22]]></Time>
<TimeTick>1507627162</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="93" Source="2、面签预约" SourceLine="19" >
<Disp><![CDATA[最终预约时间选择按钮.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1474.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0").WebButton("最终预约时间选择按钮")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="92" Source="2、面签预约" SourceLine="19" >
<Disp><![CDATA[myiframe0]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1473.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7").Frame("myiframe0")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="91" Source="2、面签预约" SourceLine="19" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1472.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Page("信贷风险管理系统V7")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[-- 网页对话框]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:25]]></Time>
<TimeTick>1507627165</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:25]]></Time>
<TimeTick>1507627165</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[myiframe0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:26]]></Time>
<TimeTick>1507627166</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[预约时间.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:26]]></Time>
<TimeTick>1507627166</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="100" Source="2、面签预约" SourceLine="20" >
<Disp><![CDATA[预约时间.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1478.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("-- 网页对话框").Page("Page").Frame("myiframe0").WebList("预约时间")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[预约时间.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["09:00"]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:26]]></Time>
<TimeTick>1507627166</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="103" Source="2、面签预约" SourceLine="21" >
<Disp><![CDATA[预约时间.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1479.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("-- 网页对话框").Page("Page").Frame("myiframe0").WebList("预约时间")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="99" Source="2、面签预约" SourceLine="20" >
<Disp><![CDATA[myiframe0]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1477.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("-- 网页对话框").Page("Page").Frame("myiframe0")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[确认.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:26]]></Time>
<TimeTick>1507627166</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="106" Source="2、面签预约" SourceLine="22" >
<Disp><![CDATA[确认.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1480.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("-- 网页对话框").Page("Page").WebElement("确认")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="98" Source="2、面签预约" SourceLine="20" >
<Disp><![CDATA[Page]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1476.xml]]></Path>
<ASHilite><![CDATA[Browser("信贷风险管理系统V7").Window("信贷风险管理系统V7").Window("-- 网页对话框").Page("Page")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="97" Source="2、面签预约" SourceLine="20" >
<Disp><![CDATA[-- 网页对话框]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1475.xml]]></Path>
<ASHilite><![CDATA[334208]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:26]]></Time>
<TimeTick>1507627166</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[ObjectList]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:26]]></Time>
<TimeTick>1507627166</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[保存.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/10/10 - 17:19:26]]></Time>
<TimeTick>1507627166</TimeTick>