<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="KF0224"><DocLocation><![CDATA[C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\02.公共脚本\信用速贷（build）]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[信用速贷（build）]]></DName>
<Res><![CDATA[Res37]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[5.3、风险参数]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[主窗口（浏览器）]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:54]]></Time>
<TimeTick>1551405834</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[一级窗口]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:54]]></Time>
<TimeTick>1551405834</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[一级窗口Page页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:54]]></Time>
<TimeTick>1551405834</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[DetailFrame_0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:54]]></Time>
<TimeTick>1551405834</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[DetailFrame_0.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:54]]></Time>
<TimeTick>1551405834</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" >
<Disp><![CDATA[DetailFrame_0.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ 风险参数 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:54]]></Time>
<TimeTick>1551405834</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="14" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ 风险参数 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="11" >
<Disp><![CDATA[DetailFrame_0]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" >
<Disp><![CDATA[一级窗口Page页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:59]]></Time>
<TimeTick>1551405839</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="16" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[一级窗口Page页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:59]]></Time>
<TimeTick>1551405839</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[一级窗口Page页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:03:59]]></Time>
<TimeTick>1551405839</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[一级窗口Page页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[myiframe0_1]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:00]]></Time>
<TimeTick>1551405840</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[myiframe0_1.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:00]]></Time>
<TimeTick>1551405840</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" >
<Disp><![CDATA[myiframe0_1.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ R0F0 ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["innertext", "贷款方案编码", "贷款方案编码", 20]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:00]]></Time>
<TimeTick>1551405840</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F0 ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="24" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ColumnCount]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="25" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="26" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="27" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="28" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="29" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="30" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="31" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="32" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="33" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="34" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="35" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="36" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="37" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ColumnCount]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="38" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="39" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="40" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="41" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="42" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ColumnCount]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="43" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="44" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="45" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="46" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="47" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ R0F5 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="49" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F5 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:02]]></Time>
<TimeTick>1551405842</TimeTick>
<NodeArgs eType="General" icon="10" nRep="50" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ R0F5 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["是"]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="52" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F5 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="General" icon="10" nRep="53" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ColumnCount]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="General" icon="10" nRep="54" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="General" icon="10" nRep="55" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="General" icon="10" nRep="56" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ R0F9 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="58" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F9 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="General" icon="10" nRep="59" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ R0F9 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["一线城市"]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="61" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F9 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="General" icon="10" nRep="62" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="General" icon="10" nRep="63" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="General" icon="10" nRep="64" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ R0F11 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:03]]></Time>
<TimeTick>1551405843</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="66" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F11 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:04]]></Time>
<TimeTick>1551405844</TimeTick>
<NodeArgs eType="General" icon="10" nRep="67" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ R0F11 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1000000.00"]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:04]]></Time>
<TimeTick>1551405844</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="69" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F11 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:04]]></Time>
<TimeTick>1551405844</TimeTick>
<NodeArgs eType="General" icon="10" nRep="70" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ColumnCount]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:04]]></Time>
<TimeTick>1551405844</TimeTick>
<NodeArgs eType="General" icon="10" nRep="71" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:04]]></Time>
<TimeTick>1551405844</TimeTick>
<NodeArgs eType="General" icon="10" nRep="72" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:04]]></Time>
<TimeTick>1551405844</TimeTick>
<NodeArgs eType="General" icon="10" nRep="73" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ R0F17 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:04]]></Time>
<TimeTick>1551405844</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="75" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F17 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:04]]></Time>
<TimeTick>1551405844</TimeTick>
<NodeArgs eType="General" icon="10" nRep="76" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ R0F17 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["否"]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="78" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F17 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="General" icon="10" nRep="79" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="General" icon="10" nRep="80" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="General" icon="10" nRep="81" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ R0F33 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="83" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F33 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="General" icon="10" nRep="84" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ R0F33 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="86" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F33 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="General" icon="10" nRep="87" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ColumnCount]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="General" icon="10" nRep="88" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="General" icon="10" nRep="89" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="General" icon="10" nRep="90" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ R0F40 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:05]]></Time>
<TimeTick>1551405845</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="92" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F40 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:06]]></Time>
<TimeTick>1551405846</TimeTick>
<NodeArgs eType="General" icon="10" nRep="93" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[[ R0F40 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["是"]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:06]]></Time>
<TimeTick>1551405846</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="95" Source="5.3、风险参数" SourceLine="-1" >
<Disp><![CDATA[[ R0F40 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2019/3/1 - 10:04:06]]></Time>
<TimeTick>1551405846</TimeTick>
<NodeArgs eType="General" icon="10" nRep="96" >
<Disp><![CDATA["[ 贷款方案编码 ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA["[ 贷款方案编码 ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>