<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="KF0224"><DocLocation><![CDATA[C:\Users\922004\Desktop\孙洪斌\学习文档集\信贷项目\02.公共脚本\信用速贷（build）]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[信用速贷（build）]]></DName>
<Res><![CDATA[Res3]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[3.2、面签信息]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[主窗口（浏览器）]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[一级窗口]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[一级窗口Page页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[myiframe0_0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ R0F0 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="12" >
<Disp><![CDATA[[ R0F0 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ R0F27 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="13" >
<Disp><![CDATA[[ R0F27 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ R0F27 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="15" >
<Disp><![CDATA[[ R0F27 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ R0F27 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["推荐人"]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="17" Source="3.2、面签信息" SourceLine="-1" >
<Disp><![CDATA[[ R0F27 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ R0F0 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[[ R0F0 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ R0F27 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" >
<Disp><![CDATA[[ R0F27 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ R0F27 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:03]]></Time>
<TimeTick>1551328863</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" >
<Disp><![CDATA[[ R0F27 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="11" >
<Disp><![CDATA[myiframe0_0]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" >
<Disp><![CDATA[一级窗口Page页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" >
<Disp><![CDATA[一级窗口]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" >
<Disp><![CDATA[主窗口（浏览器）]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[信用速贷申请]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:04]]></Time>
<TimeTick>1551328864</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:04]]></Time>
<TimeTick>1551328864</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:04]]></Time>
<TimeTick>1551328864</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[信贷风险管理系统V7.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/2/28 - 12:41:04]]></Time>
<TimeTick>1551328864</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="3.2、面签信息" SourceLine="-1" >
<Disp><![CDATA[信贷风险管理系统V7.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" Source="3.2、面签信息" SourceLine="-1" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="25" Source="3.2、面签信息" SourceLine="-1" >
<Disp><![CDATA[信贷风险管理系统V7]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="24" Source="3.2、面签信息" SourceLine="-1" >
<Disp><![CDATA[信用速贷申请]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[主窗口（浏览器）]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[一级窗口.Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="30" Source="3.2、面签信息" SourceLine="-1" >
<Disp><![CDATA[一级窗口.Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[一级窗口]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[一级窗口Page页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[myiframe0_0]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ R0F0 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" >
<Disp><![CDATA[[ R0F0 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ R0F4 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" >
<Disp><![CDATA[[ R0F4 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ R0F4 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="37" >
<Disp><![CDATA[[ R0F4 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ R0F4 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["自来客户"]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" Source="3.2、面签信息" SourceLine="-1" >
<Disp><![CDATA[[ R0F4 ].Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="33" >
<Disp><![CDATA[myiframe0_0]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" >
<Disp><![CDATA[一级窗口Page页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="31" >
<Disp><![CDATA[一级窗口]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="29" Source="3.2、面签信息" SourceLine="-1" >
<Disp><![CDATA[主窗口（浏览器）]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[找不到环境参数 &quot;BusinessType&quot;。请确认已定义具有该名称的环境参数或指定另一个环境参数。<BR>第 (31) 行: &quot;If Left(Environment(&quot;BusinessType&quot;),2)&lt;&gt;&quot;南粤&quot; Then&quot;。 ]]></Details>
<Time><![CDATA[2019/2/28 - 12:42:04]]></Time>
<TimeTick>1551328924</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="40" status="Failed" Source="3.2、面签信息" SourceLine="30" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[停止运行]]></Obj>
<Details plainTxt="False" ><![CDATA[用户停止运行。]]></Details>
<Time><![CDATA[2019/2/28 - 12:43:51]]></Time>
<TimeTick>1551329031</TimeTick>
<NodeArgs eType="General" icon="12" nRep="41" >
<Disp><![CDATA[停止运行]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2019/2/28 - 12:41:02" eTime="2019/2/28 - 12:43:51" passed="0" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[3.2、面签信息 摘要]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2019/2/28 - 12:41:01" eTime="2019/2/28 - 12:43:51" passed="0" failed="1" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[测试 信用速贷（build） 摘要]]></Disp>
</NodeArgs>
</Doc>
</Report>